// <auto-generated />
using System;
using GenZRevolutionBD.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace GenZRevolutionBD.Migrations
{
    [DbContext(typeof(SuperHeroDbContext))]
    [Migration("20240816070108_init")]
    partial class init
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("GenZRevolutionBD.Models.Power", b =>
                {
                    b.Property<int>("PowerId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("PowerId"));

                    b.Property<string>("PowerName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("PowerId");

                    b.ToTable("Powers");
                });

            modelBuilder.Entity("GenZRevolutionBD.Models.SuperHero", b =>
                {
                    b.Property<int>("SuperHeroId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("SuperHeroId"));

                    b.Property<int>("Age")
                        .HasColumnType("int");

                    b.Property<DateTime>("DateOfDeath")
                        .HasColumnType("datetime2");

                    b.Property<string>("Picture")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SuperHeroName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("SuperHeroId");

                    b.ToTable("SuperHeroes");
                });

            modelBuilder.Entity("GenZRevolutionBD.Models.SuperPower", b =>
                {
                    b.Property<int>("SuperPowerId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("SuperPowerId"));

                    b.Property<int>("PowerId")
                        .HasColumnType("int");

                    b.Property<int>("SuperHeroId")
                        .HasColumnType("int");

                    b.HasKey("SuperPowerId");

                    b.HasIndex("PowerId");

                    b.HasIndex("SuperHeroId");

                    b.ToTable("SuperPoweres");
                });

            modelBuilder.Entity("GenZRevolutionBD.Models.SuperPower", b =>
                {
                    b.HasOne("GenZRevolutionBD.Models.Power", "Power")
                        .WithMany("SuperPower")
                        .HasForeignKey("PowerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("GenZRevolutionBD.Models.SuperHero", "SuperHero")
                        .WithMany("SuperPower")
                        .HasForeignKey("SuperHeroId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Power");

                    b.Navigation("SuperHero");
                });

            modelBuilder.Entity("GenZRevolutionBD.Models.Power", b =>
                {
                    b.Navigation("SuperPower");
                });

            modelBuilder.Entity("GenZRevolutionBD.Models.SuperHero", b =>
                {
                    b.Navigation("SuperPower");
                });
#pragma warning restore 612, 618
        }
    }
}
